### PR TITLE
Add block styles with PHP

### PR DESCRIPTION
**Pull request by davidwebca**
Since 5.3.0, a register_block_style PHP function has been added and it is more reliable and prevents round trips from JavaScript to the server. This then allows allows PHP plugins and tools to filter through existing block styles before they're rendered on the admin, thus opening up the api to more possibilities (ex.: block style locations for ACF Blocks).

The JavaScript based enqueueing is left there if the PHP function doesn't exist for back compatibility.

### CODE REVIEW

**Comment by oxyc** [comment]
Hi thanks for the PR!

Feel free to drop the support for versions prior to 5.3 entirely. Would be great if you can triple check that everything works as expected too since I'd merge this without testing it myself :) (I'm only using this package on one website at the moment and it's not actively maintained)

**Comment by davidwebca** [comment]
Good, 'll make the change! I've noticed acf_register_block now takes the "styles" attribute straight into its function now so I might just refactor and pass them there, then.

I'm working on 2 projects with that PR updated package right now so I'll give it further testing in the next few hours / tomorrow. I'll update the PR when I validate everything's fine. 👍

**Comment by davidwebca** [comment]
Sorry for the delay, the holidays got in the way. 2 projects thoroughly tested this and I haven't had any problem!

**Comment by davidwebca** [comment]
As I'm working on another project using the package, I took this occasion to rephrase the readme for Acorn's "discover" command and add it to the pull request. ✌️

**Pull request merged**
